------ USER TOKEN INFO  ---------
CREATE TABLE OUATH2_TOKEN (
  USERNAME VARCHAR(50)	 NOT NULL DEFAULT '',
  TOKEN VARCHAR(1000)	 NOT NULL DEFAULT '',
  issuedDate			 VARCHAR(8) NOT NULL DEFAULT '',
  issuedTime			 VARCHAR(6) NOT NULL DEFAULT '',
  expiredDate			 VARCHAR(8) NOT NULL DEFAULT '',
  expiredTime 			 VARCHAR(6) NOT NULL DEFAULT '',
  remoteIP				 VARCHAR(255) NOT NULL DEFAULT '',
  STATUS				 VARCHAR(1) NOT NULL DEFAULT '',
  USERTYPE				 VARCHAR(2) DEFAULT '',
  PRIMARY KEY ( USERNAME )
)

------- USER INFO ----------
CREATE TABLE USER_INFO(
	USER_NAME 				VARCHAR(20) 	NOT NULL, -- USER NAME FOR LOGIN
	USER_TYPE 				VARCHAR(2) 		NOT NULL DEFAULT ''::CHARACTER VARYING, -- 01: MOBILE, 02: WEB
	USER_STATUS 			VARCHAR(2) 		NOT NULL DEFAULT ''::CHARACTER VARYING, -- 00: NORMAL, 01: DELETED, 99: DELETED
	USER_PASSWORD 			VARCHAR( 255) 	NOT NULL DEFAULT ''::CHARACTER VARYING,
	PASSWORD_CHANGE_DATE 	VARCHAR(8) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	PASSWORD_CHANGE_TIME 	VARCHAR(9) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	FIRST_LOGIN_DATE 		VARCHAR(8) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	FIRST_LOGIN_TIME 		VARCHAR(9) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	LAST_LOGIN_DATE 		VARCHAR(8) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	LAST_LOGIN_TIME 		VARCHAR(9) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	MASTER_USER_NAME 		VARCHAR(20) 	NOT NULL DEFAULT ''::CHARACTER VARYING,
	EMPLOYEE_ID				VARCHAR(20) 	NOT NULL DEFAULT ''::CHARACTER VARYING, -- RESERVE COLUMN
	CREATE_BY				VARCHAR(50)		NOT NULL, -- USER THAT CREATE
	REGISTER_DATE 			VARCHAR(8) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	REGISTER_TIME 			VARCHAR(9) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	UPDATE_DATE 			VARCHAR(8) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	UPDATE_TIME 			VARCHAR(9) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
	UPDATE_BY				VARCHAR(50) 	NOT NULL, -- USER THAT update
	CONSTRAINT PK_USER_INFO PRIMARY KEY (USER_NAME)
)

--------------------User Request Error Log --------------------------
CREATE TABLE USER_ERROR_LOG(
		USER_NAME 			VARCHAR(20) 	NOT NULL DEFAULT ''::CHARACTER VARYING,
		USER_TYPE 			VARCHAR(2) 		NOT NULL DEFAULT ''::CHARACTER VARYING, -- 01: MOBILE, 02: WEB
		REGISTER_DATE 		VARCHAR(8) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
		REGISTER_TIME 		VARCHAR(9) 		NOT NULL DEFAULT ''::CHARACTER VARYING,
		URL					VARCHAR(255) 	NOT NULL DEFAULT ''::CHARACTER VARYING,
		IP_ADDRESS 			VARCHAR(50) 	NOT NULL DEFAULT ''::CHARACTER VARYING,
		DEVICE_NAME 		VARCHAR(255) 	NOT NULL DEFAULT ''::CHARACTER VARYING,
		ERROR_CODE 			VARCHAR(255) 	NOT NULL DEFAULT ''::CHARACTER VARYING,
		ERROR_DESCRIPTION 	VARCHAR(1000) 	NOT NULL DEFAULT ''::CHARACTER VARYING,
		ERROR_CAUSE 		TEXT			NOT NULL DEFAULT ''::CHARACTER varying,
		primary key( USER_NAME,USER_TYPE,REGISTER_DATE,REGISTER_TIME)
)
