------ USER TOKEN INFO
CREATE TABLE OUATH2_TOKEN (
  USERNAME VARCHAR(50)	 NOT NULL DEFAULT '',
  TOKEN VARCHAR(1000)	 NOT NULL DEFAULT '',
  issuedDate			 VARCHAR(8) NOT NULL DEFAULT '',
  issuedTime			 VARCHAR(6) NOT NULL DEFAULT '',
  expiredDate			 VARCHAR(8) NOT NULL DEFAULT '',
  expiredTime 			 VARCHAR(6) NOT NULL DEFAULT '',
  remoteIP				 VARCHAR(255) NOT NULL DEFAULT '',
  STATUS				 VARCHAR(1) NOT NULL DEFAULT '',
  USERTYPE				 VARCHAR(2) DEFAULT '',
  PRIMARY KEY ( USERNAME )
)
